### ISSUE TITLE
Version requirements fail if a later version is installed

### ISSUE THREAD

**Issue by palfrey** [chocolatey/chocolatey-cookbook#19]
If for example I'm requesting version of a package 1.0.3 and 1.0.4 is installed, an install action will be repeatedly executed (i.e. on every chef-client run), and any notifications will be done every single time.

Could version requirements be interpreted as "that version or higher"?

**Comment by JackChance** [comment]
I feel like performing a remove then install with the earlier version is appropriate here. Lets us deal with regression conditions. Thoughts?

**Comment by ferventcoder** [comment]
@palfrey Ensure for versions I don't believe is a version range, only exact versions. One could workaround this by creating a metapackage with a dependency on 1.0.3 (which translates to that version or higher) and ensure that the metapackage is installed. It's a bit of a weird workaround though.

**Comment by tas50** [comment]
This cookbook no longer ships the package resource since that was included within Chef 12.7 which we released Feb 2016. If you're not yet on Chef 12.7 or later you'll want to upgrade, but you shouldn't see this issue anymore, especially since the 2.0 release of the cookbook removed the package resource entirely.
