### ISSUE TITLE
Allow for custom chocolatey feed

### ISSUE THREAD

**Issue by erick-thompson** [chocolatey/chocolatey-cookbook#62]
We run an internal chocolatey feed via ProGet, and would like all packages to be installed from that feedback. Is this supported at this time?

**Comment by jedugas** [comment]
Erick, my group also uses ProGet and our ProGet server is configured for Windows-authenticated feeds. Luckily for us, we back our ProGet server with an S3 bucket, so we fetch packages via S3 using a URL we generate from attribute metadata and put the package file in the local Chef cache folder (Chef::Config[:file_cache_path]).

Regardless of how you get the package to the chef node, you simply point to its download folder as the 'source' for the package.

    chocolatey some_package_name do
      source Chef::Config[:file_cache_path]
      ...

I've since written an LWRP that downloads your package directly from ProGet, decoupling the package's backing store from the process. It still requires the chocolatey resource to install the package, same as above. (If it helps, I can clean it up and push it into Github this week - it uses rubyntlm and httpclient for the Windows-authenticated download.)

Cheers
     -/- jeff

**Comment by ferventcoder** [comment]
As a workaround (if this doesn't support that), you can edit your choco config to disable the default source and set your proget source. It will be transparent to the cookbook but it will work appropriately.

**Comment by ferventcoder** [comment]
See `choco source -?`

**Comment by mwrock** [comment]
Yeah the `source` attribute simply passes the value to the `choco -source` parameter so I imagine it should work for proget.

**Comment by ferventcoder** [comment]
Also what @mwrock just stated. :)

**Comment by jedugas** [comment]
Great recommendation, I should have started there! Actually, I kind of did, but I took 'internal' to mean also 'secured' - eg. user/pwd authentication, not just an api key.

Since Chocolatey doesn't support advanced authentication scenarios, my Chef-on-the-brain example was intended to show that you have the option to first download the file (using whatever mechanism you choose) and then specify the source attribute as the download folder for the actual choco run. B^)

**Comment by mwrock** [comment]
I **think** you could get the `source` attribute working with a secured feed. It would look something like this:
```
chocolatey "some_package" do
  source "https://some.proget/feed -u blah -p blahbittyblahblah"
end
```

I have not personally tried this but its worth a try. You could also use a `powershell_script` resource to directly shell out to `choco` and create a source vis `choco source` to be referred to in future `chocolatey` resources.

**Comment by jedugas** [comment]
I've just verified Matt's claim works, so ignore my Rube Goldberg approach. Actually would recommend this in the spirit of separation-of-interests, but both work ('options' aren't documented, but the provider code makes using it quite clear):

    chocolatey "some_package" do
      source "https://some.proget/feed"
      options ({'u' => 'blah', 'p' => 'blahbittyblahblah'})
    end

cheers   B^)

**Comment by mwrock** [comment]
Glad you could confirm and agree that the use of options would be better. Need to add some readme for that for sure.
