### ISSUE TITLE
Align resource parameter "args" to choco's "params" ?

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey-cookbook#71]
Would it be possible to alias the args parameter so that it also takes the same name as choco ("params")?

**Comment by mwrock** [comment]
The `args` attributye actually alligns with the `--installargs` parameter, not `params`.

**Comment by ferventcoder** [comment]
probably need something for params :)

**Comment by mwrock** [comment]
Well there is the `options` attribute which is a hash of of arguments to send to `choco.exe`:
```
chocolatey "some_package" do
  options ({'params' => 'my_value'})
end
```
Not sure we want to create one to one mappings of resource attributes to choco parameters.

**Comment by ferventcoder** [comment]
Ah, well that works as well. :)

**Comment by Techcadia** [comment]
https://chocolatey.org/docs/commands-reference#how-to-pass-options-switches
Figured I would leave this hear so that other could find it.

Today I spent a few more than a I care to admit fighting with a missing set of quotes when passing in parameters from chef to choco.


My final solution was double double quotes.
