### ISSUE TITLE
chocolatey_source resource

### ISSUE THREAD

**Issue by docwhat** [chocolatey/chocolatey-cookbook#84]
It would be nice to have a `chocolatey_source` resource to manage/manipulate the sources.

Examples:

```
chocolatey_source 'chocolatey' do
  source 'https://chocolatey.org/api/v2/'
  priority 0
end

chocolatey_source 'private' do
  source 'https://nexus.example.com/service/local/nuget/chocolatey`
  username 'joecool'
  password 'sekret'
  priority 10
end
```

**Comment by mwrock** [comment]
Agreed. I can see that being useful.

**Comment by Plork** [comment]
+1 for this ;)

**Comment by donbecker** [comment]
+ 1 this seems like it aligns with other (non-Windows) package managers.

**Comment by michaeltlombardi** [comment]
It'd also be useful to be able to use the resource to _remove_ sources (such as the community feed).

**Comment by tas50** [comment]
I've written a new chocolatey_source cookbook that handles sources setup. This includes a single resource and the intention is to ship this same resource directly in Chef at which point we'll deprecate the cookbook. I didn't want to include that within the chocolatey cookbook since we'll just be moving that functionality internally. If you do need still need to setup sources give it a try.

https://supermarket.chef.io/cookbooks/chocolatey_source
